//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaCity.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectionRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectionRoom()
        {
            this.Projections = new HashSet<Projection>();
        }
    
        public int ID { get; set; }
        public byte Number { get; set; }
        public int Seats { get; set; }
        public string Type { get; set; }
        public int CinemaId { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projection> Projections { get; set; }
    }
}
