//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaCity.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projection()
        {
            this.ProjectionMovies = new HashSet<ProjectionMovy>();
        }
    
        public int ID { get; set; }
        public System.DateTime Start { get; set; }
        public decimal Price { get; set; }
        public int ProjectionRoomID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectionMovy> ProjectionMovies { get; set; }
        public virtual ProjectionRoom ProjectionRoom { get; set; }
    }
}
