//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaCity.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectionMovy
    {
        public int Id { get; set; }
        public int ProjectionId { get; set; }
        public int MovieId { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Projection Projection { get; set; }
    }
}
