//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaCityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaCityEntities : DbContext
    {
        public CinemaCityEntities()
            : base("name=CinemaCityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<ProjectionMovy> ProjectionMovies { get; set; }
        public virtual DbSet<ProjectionRoom> ProjectionRooms { get; set; }
        public virtual DbSet<Projection> Projections { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
