//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaCityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectionMovy
    {
        public int ID { get; set; }
        public int ProjectionID { get; set; }
        public int FilmID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Projection Projection { get; set; }
    }
}
